# Generated by Django 2.2.10 on 2020-03-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
        ('battles', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team',
            field=models.ManyToManyField(to='pokemon.Pokemon', verbose_name='Team'),
        ),
    ]
