# Generated by Django 2.2.10 on 2020-03-03 17:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0003_team_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
