# Generated by Django 2.2.10 on 2020-03-04 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0004_battle_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='battle',
        ),
    ]
