# Generated by Django 2.2.11 on 2020-03-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0006_team_battle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
