# Generated by Django 2.2.11 on 2020-03-09 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0007_auto_20200309_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='user_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_battle', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='user_opponent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_to_battle', to=settings.AUTH_USER_MODEL, verbose_name='Opponent'),
        ),
        migrations.AlterField(
            model_name='team',
            name='battle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='battles.Battle'),
        ),
        migrations.AlterField(
            model_name='team',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='Trainer'),
        ),
    ]
