# Generated by Django 2.2.11 on 2020-03-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0008_auto_20200309_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='settled',
            field=models.BooleanField(default=False),
        ),
    ]
