# Generated by Django 2.2.11 on 2020-04-01 16:53

from django.db import migrations

def pokemon_in_team_becomes_foreignkey(apps, schema_editor):
    Team = apps.get_model('battles', 'Team')
    for team in Team.objects.all():
        pokemon = team.team.all()
        team.first_pokemon = pokemon[0]
        team.second_pokemon = pokemon[1]
        team.third_pokemon = pokemon[2]
        team.save()

class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0012_auto_20200401_1640'),
    ]

    operations = [
        migrations.RunPython(pokemon_in_team_becomes_foreignkey),
    ]
