# Generated by Django 2.2.11 on 2020-04-01 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0013_auto_20200401_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team',
        ),
        migrations.AlterField(
            model_name='team',
            name='first_pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_pokemon', to='pokemon.Pokemon'),
        ),
        migrations.AlterField(
            model_name='team',
            name='second_pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_pokemon', to='pokemon.Pokemon'),
        ),
        migrations.AlterField(
            model_name='team',
            name='third_pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_pokemon', to='pokemon.Pokemon'),
        ),
    ]
